/// Phase-2 hermetic known-vector test for the byte-identical TS↔Move signing
/// path.
///
/// Feature: yeti-trials-backend, Property 1: Signing-path byte-identity round-trip
///
/// A FIXED Ed25519 keypair (the deterministic conformance seed) signs a single
/// KNOWN `ProofPayload` in TypeScript; the signature, the serialized
/// `Signed_Message`, the nullifier, and the public key are checked in below.
/// This test reconstructs the same payload in Move and asserts:
///   * the Move-reconstructed `Signed_Message` bytes equal the TS bytes
///     (byte identity — Requirements 4.1, 4.2, 4.3, 4.6);
///   * the genuine 64-byte signature verifies (Requirements 4.4, 4.5);
///   * a single flipped bit in the message OR the signature makes verification
///     fail.
///
/// If byte identity ever breaks, compare `proof::payload_bcs_bytes(&payload)`
/// against the TS `serializeProofPayload(payload)` hex field-by-field; the most
/// likely culprit is a BigInt/number slip or a field-order mismatch.
#[test_only]
module yeti_trials::proof_tests;

use sui::ed25519;
use yeti_trials::proof;

// Abort code mirrored from `yeti_trials::constants` (private module const),
// kept in sync by value (E_INVALID_SIGNATURE = 7).
const E_INVALID_SIGNATURE: u64 = 7;

// --- Checked-in known vector (generated by the fixed conformance keypair) ---

fun known_pk(): vector<u8> {
    vector[121, 181, 86, 46, 143, 230, 84, 249, 64, 120, 177, 18, 232, 169, 139, 167, 144, 31, 133, 58, 230, 149, 190, 215, 224, 227, 145, 11, 173, 4, 150, 100]
}

fun known_signature(): vector<u8> {
    vector[3, 250, 129, 231, 115, 207, 221, 3, 244, 141, 61, 48, 16, 212, 246, 43, 135, 207, 177, 65, 45, 216, 65, 38, 50, 176, 119, 16, 43, 90, 50, 125, 81, 234, 112, 42, 150, 73, 221, 30, 73, 69, 123, 122, 122, 238, 58, 88, 150, 152, 146, 69, 197, 70, 145, 206, 99, 132, 39, 165, 169, 203, 29, 12]
}

fun known_nullifier(): vector<u8> {
    vector[182, 17, 238, 7, 80, 64, 221, 96, 23, 96, 27, 149, 39, 152, 66, 47, 120, 224, 92, 191, 79, 40, 224, 187, 229, 100, 49, 101, 77, 38, 102, 27]
}

fun known_signed_message(): vector<u8> {
    vector[89, 101, 116, 105, 32, 84, 114, 105, 97, 108, 115, 8, 108, 111, 99, 97, 108, 110, 101, 116, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 42, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 1, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 26, 79, 114, 97, 99, 108, 101, 45, 65, 116, 116, 101, 115, 116, 101, 100, 32, 68, 101, 109, 111, 32, 80, 114, 111, 111, 102, 2, 210, 4, 0, 0, 0, 0, 0, 0, 55, 2, 0, 0, 0, 0, 0, 0, 0, 104, 229, 207, 139, 1, 0, 0, 192, 143, 238, 207, 139, 1, 0, 0, 99, 0, 0, 0, 0, 0, 0, 0, 32, 182, 17, 238, 7, 80, 64, 221, 96, 23, 96, 27, 149, 39, 152, 66, 47, 120, 224, 92, 191, 79, 40, 224, 187, 229, 100, 49, 101, 77, 38, 102, 27]
}

/// Reconstruct the known payload from its typed fields.
fun known_payload(): proof::ProofPayload {
    proof::build_payload(
        b"localnet",
        @0x1111111111111111111111111111111111111111111111111111111111111111,
        42, // season_id
        7, // trial_id
        1, // faction_id (Avalanche)
        @0x2222222222222222222222222222222222222222222222222222222222222222,
        @0x3333333333333333333333333333333333333333333333333333333333333333,
        b"Oracle-Attested Demo Proof",
        2, // provenance_tier (Oracle-Attested)
        1234, // score
        567, // territory_power
        1700000000000, // issued_ms
        1700000600000, // expiry_ms
        99, // nonce
        known_nullifier(),
    )
}

// Feature: yeti-trials-backend, Property 1: Signing-path byte-identity round-trip
//
// The Move-reconstructed Signed_Message bytes equal the TS-serialized bytes.
#[test]
fun byte_identity_matches_typescript() {
    let payload = known_payload();
    assert!(proof::signed_message_bytes(&payload) == known_signed_message(), 0);
    // The nullifier the Move side recomputes from the preimage matches too.
    let computed = proof::compute_nullifier(
        42,
        7,
        1,
        @0x2222222222222222222222222222222222222222222222222222222222222222,
        @0x3333333333333333333333333333333333333333333333333333333333333333,
        99,
    );
    assert!(computed == known_nullifier(), 1);
}

// Feature: yeti-trials-backend, Property 1: Signing-path byte-identity round-trip
//
// The genuine 64-byte Ed25519 signature verifies against the reconstructed
// message and the fixed public key.
#[test]
fun valid_signature_verifies_true() {
    let payload = known_payload();
    let sig = known_signature();
    let pk = known_pk();
    assert!(proof::verify_payload_signature(&payload, &sig, &pk), 0);
}

// Feature: yeti-trials-backend, Property 1: Signing-path byte-identity round-trip
//
// A single flipped bit in the SIGNATURE makes verification fail.
#[test]
fun flipped_signature_bit_verifies_false() {
    let payload = known_payload();
    let mut sig = known_signature();
    let b0 = *vector::borrow(&sig, 0);
    *vector::borrow_mut(&mut sig, 0) = b0 ^ 1u8;
    let pk = known_pk();
    assert!(!proof::verify_payload_signature(&payload, &sig, &pk), 0);
}

// Feature: yeti-trials-backend, Property 1: Signing-path byte-identity round-trip
//
// A single flipped bit in the MESSAGE makes verification fail.
#[test]
fun flipped_message_bit_verifies_false() {
    let mut msg = known_signed_message();
    let i = 20; // a byte inside the BCS body (past the 11-byte domain prefix)
    let b = *vector::borrow(&msg, i);
    *vector::borrow_mut(&mut msg, i) = b ^ 1u8;
    let sig = known_signature();
    let pk = known_pk();
    assert!(!ed25519::ed25519_verify(&sig, &pk, &msg), 0);
}

// Feature: yeti-trials-backend, Property 1: Signing-path byte-identity round-trip
//
// The abort-path helper aborts E_INVALID_SIGNATURE on a bad signature.
#[test]
#[expected_failure(abort_code = E_INVALID_SIGNATURE, location = yeti_trials::proof)]
fun assert_valid_signature_aborts_on_bad_sig() {
    let payload = known_payload();
    let mut sig = known_signature();
    let b0 = *vector::borrow(&sig, 0);
    *vector::borrow_mut(&mut sig, 0) = b0 ^ 1u8;
    let pk = known_pk();
    proof::assert_valid_signature(&payload, &sig, &pk);
}
